In [10]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\ROHAN\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
# importn
import pandas as pd

In [11]:

#tuple
s3=pd.Series((1, 2, 3, 4, 5))
print("Tuples=")
print(s3)

Tuples=
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
#list
s4=pd.Series([1, 2, 3, 4, 5])
print("List=")
print(s4)

List=
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
#string
s5=pd.Series("Hello World")
print("String=")
print(s5)

String=
0    Hello World
dtype: str

In [14]:
#create a series (data,index,dtype)
pd.Series(range(5), index=['a', 'b', 'c', 'd', 'e'], dtype='float64')

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [15]:
#create a series with names
s = pd.Series(['sujal,', 'rohan', 'sachin'])
print(s)

0    sujal,
1     rohan
2    sachin
dtype: str

In [16]:
#properties of series
s.index

RangeIndex(start=0, stop=3, step=1)

In [18]:
pd.__version__

'3.0.6'

In [17]:
s.values

<StringArray>
['sujal,', 'rohan', 'sachin']
Length: 3, dtype: str

In [19]:
#check data type
s.dtype

In [20]:
#check dimension
s.ndim

1

In [21]:
#check total number of elements
s.size

3

In [22]:
#check shape
s.shape

(3,)

In [24]:
s.str.title()

0    Sujal,
1     Rohan
2    Sachin
dtype: str

In [28]:
#create a dataframe
d = pd.DataFrame({
    'name': ['sujal powar', 'rohan jangale', 'sachin tendulkar'],
    'age': [20, 21, 22],  
    'Salary': [10000, 20000, 30000]   
})
d

               name  age  Salary
0       sujal powar   20   10000
1     rohan jangale   21   20000
2  sachin tendulkar   22   30000

In [29]:
import pandas as pd

data = [[1, 'rohan'], [2, 'snehajeet'], [3, 'salman']]

df1 = pd.DataFrame(data, columns=['ID', 'Name'])
print(df1)

   ID       Name
0   1      rohan
1   2  snehajeet
2   3     salman

In [32]:
df1.shape

(3, 2)

In [34]:
df1.dtypes

ID      int64
Name      str
dtype: object

In [35]:
df1.ndim

2

In [36]:
#convert dataframe  to array
df1.values

array([[1, 'rohan'],
       [2, 'snehajeet'],
       [3, 'salman']], dtype=object)

In [40]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ------ -------------------------------- 41.0/250.9 kB 653.6 kB/s eta 0:00:01
   ------------------- -------------------- 122.9/250.9 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.5 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\ROHAN\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\rohan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\ROHAN\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [44]:
# convert to xcel files
d.to_excel('data.xlsx', index=False)

In [ ]:
#select one column
#d['name'] first way
#d.name second way
# loc- label based selection , we can work on both rows and columns

d.loc[2:,['name','age','Salary']] # in loc stop is inclusive-  intervie question

               name  age  Salary
2  sachin tendulkar   22   30000

In [62]:
d.iloc[0:,1::] # in iloc stop is exclusive-  intervie question

   age  Salary
0   20   10000
1   21   20000
2   22   30000

In [65]:
#access the data of person whose salary is maximum
d['Salary'].max()

np.int64(30000)

In [ ]:
d.query('Salarry==Salary.max()'A)

               name  age  Salary
2  sachin tendulkar   22   30000

In [68]:
d['age'].min()

np.int64(20)

In [69]:
d.query('age==age.min()')

          name  age  Salary
0  sujal powar   20   10000

In [70]:
d['Salary']>10000

0    False
1     True
2     True
Name: Salary, dtype: bool

In [71]:
# salary greate then 100000
d.query('Salary>10000')

               name  age  Salary
1     rohan jangale   21   20000
2  sachin tendulkar   22   30000

In [73]:
d['name']. apply(lambda nm: nm.split()[0])

0     sujal
1     rohan
2    sachin
Name: name, dtype: str

In [ ]:
d['f_name'] = d['name']. apply(lambda nm: nm.split()[0]) # for ading column of first name
d['l_name'] = d['name']. apply(lambda nm: nm.split()[1]) # for ading column of last name

In [82]:
d

               name  age  Salary  f_name     l_name
0       sujal powar   20   10000   sujal      powar
1     rohan jangale   21   20000   rohan    jangale
2  sachin tendulkar   22   30000  sachin  tendulkar

In [84]:
# add a new column with 10% raise   
d['New_Salary'] = d['Salary'] + (d['Salary'] * 0.1)

In [85]:
d

               name  age   Salary  f_name     l_name  New_Salary
0       sujal powar   20  11000.0   sujal      powar     12100.0
1     rohan jangale   21  22000.0   rohan    jangale     24200.0
2  sachin tendulkar   22  33000.0  sachin  tendulkar     36300.0

In [86]:
# add a column with constant value
d['Company'] = 'Liha Tech'

In [90]:
#delete the column
d.drop('Salary', axis=1, inplace=True)

In [91]:
d

               name  age  f_name     l_name  New_Salary    Company
0       sujal powar   20   sujal      powar     12100.0  Liha Tech
1     rohan jangale   21   rohan    jangale     24200.0  Liha Tech
2  sachin tendulkar   22  sachin  tendulkar     36300.0  Liha Tech

In [93]:
#fetch the name whose names satrts with 'r'
d.query('name.str.startswith("r")')

            name  age f_name   l_name  New_Salary    Company
1  rohan jangale   21  rohan  jangale     24200.0  Liha Tech

In [ ]:
path ="CO2_Emissions_Canada_Beginner_Pandas_Practice.ipynb"

f = pd.read_csv(path)
f.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'CO2_Emissions_Canada_Beginner_Pandas_Practice.ipynb'

In [95]:
f.shape

(18207, 18)

In [132]:
f.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,p_foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [97]:
f.info()  # it will gibe u the information about the data like how many rows and columns are there, what is the data type of each column, how many non-null values are there in each column, etc.

<class 'pandas.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  str
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  str
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  str
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  str
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  str
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  str
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), str(6)
memory usage: 2.5 MB

In [101]:
# chekc the missing values in the dataset
f.isnull().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [105]:
#handle mising valuesin the dataset
f['Club'].fillna('unknown club', inplace=True)

C:\Users\ROHAN\AppData\Local\Temp\ipykernel_15636\3241976315.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  f['Club'].fillna('unknown club', inplace=True)

0               FC Barcelona
1                   Juventus
2        Paris Saint-Germain
3          Manchester United
4            Manchester City
                ...
18202        Crewe Alexandra
18203         Trelleborgs FF
18204       Cambridge United
18205        Tranmere Rovers
18206        Tranmere Rovers
Name: Club, Length: 18207, dtype: str

In [106]:
#delete rows with missing values
f.dropna(inplace=True)

In [107]:
f.isna().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred Foot              0
International Reputation    0
Skill Moves                 0
Position                    0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

In [108]:
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='str')

In [112]:
f['Skill Moves']

0        4.0
1        5.0
2        5.0
3        1.0
4        4.0
        ...
18202    2.0
18203    2.0
18204    2.0
18205    2.0
18206    2.0
Name: Skill Moves, Length: 17907, dtype: float64

In [113]:
# change the column names
f.rename(columns={'Preferred Foot': 'p_foot'}, inplace=True)

In [114]:
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'p_foot', 'International Reputation', 'Skill Moves',
       'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight',
       'Release Clause'],
      dtype='str')

In [115]:
#replace column names where space is there with underscore
f.columns = f.columns.str.replace(' ', '_')

In [116]:
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'p_foot', 'International_Reputation', 'Skill_Moves',
       'Position', 'Joined', 'Contract_Valid_Until', 'Height', 'Weight',
       'Release_Clause'],
      dtype='str')

In [ ]:
#fetch a record of player from the particular club 
f['Club'].unique() # will give u a unqui club nmaes

<StringArray>
[       'FC Barcelona',            'Juventus', 'Paris Saint-Germain',
   'Manchester United',     'Manchester City',             'Chelsea',
         'Real Madrid',     'Atlético Madrid',   'FC Bayern München',
   'Tottenham Hotspur',
 ...
   'IF Brommapojkarna',     'Crewe Alexandra',         'Yeovil Town',
         'Bohemian FC',   'Macclesfield Town',      'Newport County',
        'Sligo Rovers',          'Derry City',         'Limerick FC',
      'Bray Wanderers']
Length: 651, dtype: str

In [122]:
f['Club'].value_counts() # will give total no of unique clubs with

Club
FC Barcelona           33
Manchester United      33
Manchester City        33
Chelsea                33
Real Madrid            33
                       ..
Ceará Sporting Club    20
Tromsø IL              20
Sligo Rovers           19
Limerick FC            19
Derry City             18
Name: count, Length: 651, dtype: int64

In [123]:
f.dtypes

ID                            int64
Name                            str
Age                           int64
Nationality                     str
Overall                       int64
Potential                     int64
Club                            str
Value                       float64
Wage                        float64
p_foot                          str
International_Reputation    float64
Skill_Moves                 float64
Position                        str
Joined                        int64
Contract_Valid_Until            str
Height                      float64
Weight                      float64
Release_Clause              float64
dtype: object

In [125]:
f.select_dtypes(include='object' ).columns #e u the columns which are of object data type

C:\Users\ROHAN\AppData\Local\Temp\ipykernel_15636\395583567.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  f.select_dtypes(include='object' ).columns #e u the columns which are of object data type

Index(['Name', 'Nationality', 'Club', 'p_foot', 'Position',
       'Contract_Valid_Until'],
      dtype='str')

In [126]:
f['Name'].value_counts()

Name
J. Rodríguez          11
Paulinho               8
J. Williams            7
Felipe                 6
J. Hernández           6
                      ..
D. Walsh               1
N. Christoffersson     1
B. Worman              1
D. Walker-Rice         1
G. Nugent              1
Name: count, Length: 16913, dtype: int64

In [127]:
f['Nationality'].value_counts()

Nationality
England        1655
Germany        1195
Spain          1071
Argentina       935
France          910
               ...
Malta             1
Belize            1
South Sudan       1
Indonesia         1
Botswana          1
Name: count, Length: 163, dtype: int64

In [130]:
# a player from real madrid whose age is greater than 30
f.query('Club=="Real Madrid" and Age<30')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,p_foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
11,182521,T. Kroos,28,Germany,90,90,Real Madrid,76500.0,355.0,Right,4.0,3.0,LCM,2014,2022-01-01,6.000000,168.0,156800.0
19,192119,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0
27,200145,Casemiro,26,Brazil,88,90,Real Madrid,59500.0,285.0,Right,3.0,2.0,CDM,2013,2021-01-01,6.083333,185.0,126400.0
30,197781,Isco,26,Spain,88,91,Real Madrid,73500.0,315.0,Right,3.0,4.0,LW,2013,2022-01-01,5.750000,174.0,156200.0
36,173731,G. Bale,28,Wales,88,88,Real Madrid,60000.0,355.0,Left,4.0,4.0,ST,2013,2022-01-01,6.083333,181.0,123000.0
62,201535,R. Varane,25,France,86,91,Real Madrid,50000.0,210.0,Right,3.0,2.0,RCB,2011,2022-01-01,6.250000,179.0,106300.0
79,220834,Marco Asensio,22,Spain,85,92,Real Madrid,54000.0,215.0,Left,3.0,4.0,RW,2015,2023-01-01,6.000000,168.0,121500.0
123,204963,Carvajal,26,Spain,84,87,Real Madrid,31500.0,185.0,Right,3.0,3.0,RB,2013,2022-01-01,5.666667,161.0,66900.0
172,208618,Lucas Vázquez,27,Spain,83,83,Real Madrid,27000.0,205.0,Right,2.0,4.0,RW,2015,2021-01-01,5.666667,154.0,55400.0
188,200724,Nacho Fernández,28,Spain,83,85,Real Madrid,24500.0,180.0,Right,2.0,2.0,CB,2010,2021-01-01,5.916667,168.0,52100.0
328,222509,Dani Ceballos,21,Spain,81,88,Real Madrid,25000.0,120.0,Right,1.0,4.0,LCM,2017,2023-01-01,5.833333,154.0,56300.0
417,234035,Odriozola,22,Spain,80,88,Real Madrid,18500.0,115.0,Right,1.0,3.0,RB,2018,2024-01-01,5.750000,146.0,41600.0
430,221639,Mariano,24,Dominican Republic,80,85,Real Madrid,20000.0,140.0,Right,1.0,3.0,ST,2018,2023-01-01,5.916667,168.0,42500.0
573,226161,Marcos Llorente,23,Spain,79,87,Real Madrid,16000.0,110.0,Right,1.0,3.0,CDM,2014,2021-01-01,6.000000,161.0,36000.0
754,225161,Vallejo,21,Spain,78,86,Real Madrid,13500.0,81.0,Right,1.0,2.0,CB,2015,2021-01-01,6.000000,174.0,30400.0
1143,238794,Vinícius Júnior,17,Brazil,77,92,Real Madrid,17500.0,66.0,Right,1.0,5.0,LW,2018,2025-01-01,5.750000,161.0,46800.0
2513,239053,F. Valverde,19,Uruguay,74,84,Real Madrid,8500.0,46.0,Right,1.0,3.0,CM,2016,2021-01-01,6.000000,172.0,19100.0
6724,245279,Reguilón,21,Spain,68,80,Real Madrid,1400.0,28.0,Left,1.0,3.0,LB,2017,2020-01-01,5.833333,150.0,3200.0
8732,245238,Javi Sánchez,21,Spain,67,79,Real Madrid,1200.0,24.0,Right,1.0,2.0,CB,2016,2019-01-01,6.166667,170.0,2700.0
9141,225105,Cristo González,20,Spain,66,78,Real Madrid,1200.0,26.0,Right,1.0,3.0,ST,2017,2019-01-01,5.833333,163.0,2600.0
10178,241467,F. Feuillassier,20,Argentina,65,80,Real Madrid,1200.0,23.0,Right,1.0,3.0,LW,2017,2019-01-01,5.666667,152.0,3200.0
10269,246608,Fidalgo,21,Spain,65,75,Real Madrid,875.0,20.0,Right,1.0,3.0,CM,2016,2019-01-01,5.750000,150.0,2000.0
11163,245287,Sergio López,19,Spain,64,80,Real Madrid,875.0,9.0,Right,1.0,3.0,RB,2018,2019-01-01,5.833333,146.0,2300.0
11327,246606,Fran García,18,Spain,64,79,Real Madrid,825.0,9.0,Left,1.0,2.0,LB,2018,2019-01-01,5.583333,139.0,2200.0
11877,243155,Manu Hernando,19,Spain,64,76,Real Madrid,700.0,9.0,Right,1.0,2.0,CB,2017,2021-01-01,5.916667,170.0,1600.0
12504,243315,Dani Gómez,19,Spain,63,77,Real Madrid,800.0,12.0,Right,1.0,2.0,ST,2017,2022-01-01,5.833333,154.0,2100.0
13687,240311,L. Zidane,20,France,62,71,Real Madrid,350.0,9.0,Right,1.0,1.0,GK,2016,2019-01-01,6.000000,170.0,788.0

In [1]:
# first question of classwork
f.query('Nationality == "Spain" & Contract_Valid_Until == "2025-01-01"')

NameError: name 'f' is not defined

In [148]:
#second question of classork
# which club gives highest average wages

# assignment 1

In [6]:
#Question 1
#Import the Pandas library using the alias pd and read CO2 Emissions_Canada.csv into a DataFrame named df.



import pandas as pd

url = "https://raw.githubusercontent.com/piyush-malu/CO2-Emission-by-Vehicles/main/CO2%20Emissions_Canada.csv"

df = pd.read_csv(url)

print(df)

       Make        Model   Vehicle Class  Engine Size(L)  Cylinders  \
0     ACURA          ILX         COMPACT             2.0          4
1     ACURA          ILX         COMPACT             2.4          4
2     ACURA   ILX HYBRID         COMPACT             1.5          4
3     ACURA      MDX 4WD     SUV - SMALL             3.5          6
4     ACURA      RDX AWD     SUV - SMALL             3.5          6
...     ...          ...             ...             ...        ...
7380  VOLVO  XC40 T5 AWD     SUV - SMALL             2.0          4
7381  VOLVO  XC60 T5 AWD     SUV - SMALL             2.0          4
7382  VOLVO  XC60 T6 AWD     SUV - SMALL             2.0          4
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD             2.0          4
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD             2.0          4

     Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
0             AS5         Z                               9.9
1              M6         Z                              11.2
2             AV7         Z                               6.0
3             AS6         Z                              12.7
4             AS6         Z                              12.1
...           ...       ...                               ...
7380          AS8         Z                              10.7
7381          AS8         Z                              11.2
7382          AS8         Z                              11.7
7383          AS8         Z                              11.2
7384          AS8         Z                              12.2

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                                 6.7                               8.5
1                                 7.7                               9.6
2                                 5.8                               5.9
3                                 9.1                              11.1
4                                 8.7                              10.6
...                               ...                               ...
7380                              7.7                               9.4
7381                              8.3                               9.9
7382                              8.6                              10.3
7383                              8.3                               9.9
7384                              8.7                              10.7

      Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
0                              33                  196
1                              29                  221
2                              48                  136
3                              25                  255
4                              27                  244
...                           ...                  ...
7380                           30                  219
7381                           29                  232
7382                           27                  240
7383                           29                  232
7384                           26                  248

[7385 rows x 12 columns]

In [12]:
#Question 2
#Display the first 5 rows of the dataset.
df.head(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244